---
title: "R Notebook"
output: html_notebook
---


```{r}
getwd()
mapD = read.table("/Users/Yibing/Bioinfo-Master-Thesis/Data/mapdScore.250K.101.gamma15.txt", sep = "\t", header = TRUE)
mapD.select = subset(mapD, mapD$mapd<0.6)
write.csv(mapD.select, file = "mapD_selected.csv")


```

```{r}
embryoNumber = c(1,2,3,4,5,6,7,8,9,
                 10,11,12,13,14,15,16,17,18,19,
                 20,21,22,23,24,25,26,27,28,29,
                 30,31,32,33,34,35,36,37,38,39,
                 40,41,42,43,44,45,46,47)
cellNumber = list(c(1),c(1),c(1,2),c(1,2),c(1),c(1,2,3),c(1,2),c(1,2,3),c(2,3),
                  c(2,4),c(2,3,4,6,7,9,10),c(1,2,4,7),c(1), c(3,5,6),c(1,2,3),c(1,4),c(2,3,5,7,8,9,10),c(1,2,3,4,5,6,7,8,9,11,12),c(2),
                  c(1,2,3),c(2,3),c(1,2),c(1),c(1,2,3),c(1,2,3,4),c(3,4,5),c(1,2,3,5),c(1,2),c(1,4),
                  c(1,2,3,4),c(1),c(3,4,5,6,7,8,9),c(1,2,3,4,5,6,7,8,9,11,12),c(2),c(1,2,3,4),c(1),c(1,2),c(1,2,3,4),c(1,2),
                  c(7,8,9,10,11,12,13,14,15,17,18,19,21,22,24,25),c(1,2,3,4,5,6,7),c(1,2,3,4,5,7,8),c(1,2,3,4,5,6),c(1,2,4,5,6,7,8,9,10,11,13,14,15,16,17,18,22,24,25,26,28,29,31,32,33,35,36,37,38,39),c(1,2,4,5,8,9,10,11,12,13),c(2,3,5,6,7,8,9,10,11,12,13,15,16,17,18,21,22),c(15,16,17,18,20,21,22,23,24,25,26,27,28,29,30))

for (i in 1:length(embryoNumber)){
  fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn_per_bin/TVEMB", (embryoNumber[i])[1], sep = ""), (unlist(cellNumber[i]))[1], sep = "_"), "250K.101.sorted.count.gamma_15.gc_corrected.segments.copynumber.txt", sep = ".")  
  data = read.table(fileName, sep = "\t", header = TRUE)
  data = data[c(1:3)]
  
  for (n in 1:length(as.numeric(unlist(cellNumber[i])))){ 
    fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn_per_bin/TVEMB", embryoNumber[i], sep = ""), (unlist(cellNumber[i]))[n], sep = "_"), "250K.101.sorted.count.gamma_15.gc_corrected.segments.copynumber.txt", sep = ".")  
    columnName = paste("LogR", paste(embryoNumber[i], (unlist(cellNumber[i]))[n], sep = "_"), sep = "_")
    data[columnName] = read.table(fileName, sep = "\t", header = TRUE)[6]
    writeFileName = paste(paste("embryo", embryoNumber[i], sep = ""), "logR.csv", sep = "_")
    write.csv(data, file = writeFileName)
    
  }
}



```

