---
title: "R Notebook"
output: html_notebook
---
```{r}
library(ggplot2)
library(matrixStats)
library(reshape)
```

```{r}
install.packages("readxl")
library(readxl)
embryo_master_dataset = read_excel("/Users/Yibing/Bioinfo-Master-Thesis/Data/embryo_master_dataset.xlsx")
embryo_stage = embryo_master_dataset[c(6, 15)]

embryoNumber = c(1,2,3,4,5,6,7,8,9,
                 10,11,12,13,14,15,16,17,18,19,
                 20,21,22,23,24,25,26,27,28,29,
                 30,31,32,33,34,35,36,37,38,39,
                 40,41,42,43,44,45,46,47)
cellNumber = list(c(1),c(1),c(1,2),c(1,2),c(1),c(1,2,3),c(1,2),c(1,2,3),c(2,3),
                  c(2,4),c(2,3,4,6,7,9,10),c(1,2,4,7),c(1), c(3,5,6),c(1,2,3),c(1,4),c(2,3,5,7,8,9,10),c(1,2,3,4,5,6,7,8,9,11,12),c(2),
                  c(1,2,3),c(2,3),c(1,2),c(1),c(1,2,3),c(1,2,3,4),c(3,4,5),c(1,2,3,5),c(1,2),c(1,4),
                  c(1,2,3,4),c(1),c(3,4,5,6,7,8,9),c(1,2,3,4,5,6,7,8,9,11,12),c(2),c(1,2,3,4),c(1),c(1,2),c(1,2,3,4),c(1,2),
                  c(7,8,9,10,11,12,13,14,15,17,18,19,21,22,24,25),c(1,2,3,4,5,6,7),c(1,2,3,4,5,7,8),c(1,2,3,4,5,6),c(1,2,4,5,6,7,8,9,10,11,13,14,15,16,17,18,22,24,25,26,28,29,31,32,33,35,36,37,38,39),c(1,2,4,5,8,9,10,11,12,13),c(2,3,5,6,7,8,9,10,11,12,13,15,16,17,18,21,22),c(15,16,17,18,20,21,22,23,24,25,26,27,28,29,30))

#get cell id for different stages
embryo_stage_day1 = subset(embryo_stage, embryo_stage$Stage=="day1")
embryoNumber_day1 = c(1,2,3,19,20,21,22,23,34,35,36,37,38,39)
cellNumber_day1 = list(c(1),c(1),c(1,2),c(2),c(1,2,3),c(2,3),c(1,2),c(1),c(2),c(1,2,3,4),c(1),c(1,2),c(1,2,3,4),c(1,2))

embryo_stage_day2 = subset(embryo_stage, embryo_stage$Stage=="day2")
embryoNumber_day2 = c(4,5,6,7,8,9,10,13,14,15,16,24,25,26,27,28,29,30,31)
cellNumber_day2 = list(c(1,2),c(1),c(1,2,3),c(1,2),c(1,2,3),c(2,3),c(2,4),c(1), c(3,5,6),c(1,2,3),c(1,4),c(1,2,3),c(1,2,3,4),c(3,4,5),c(1,2,3,5),c(1,2),c(1,4),c(1,2,3,4),c(1))

embryo_stage_day3 = subset(embryo_stage, embryo_stage$Stage=="day3")
embryoNumber_day3 = c(11,12,41,42,43)
cellNumber_day3 = list(c(2,3,4,6,7,9,10),c(1,2,4,7),c(1,2,3,4,5,6,7),c(1,2,3,4,5,7,8),c(1,2,3,4,5,6))

embryo_stage_day4 = subset(embryo_stage, embryo_stage$Stage=="day4")
embryoNumber_day4 = c(17,18,32,33,45,46)
cellNumber_day4 = list(c(2,3,5,7,8,9,10),c(1,2,3,4,5,6,7,8,9,11,12),c(3,4,5,6,7,8,9),c(1,2,3,4,5,6,7,8,9,11,12),c(1,2,4,5,8,9,10,11,12,13),c(2,3,5,6,7,8,9,10,11,12,13,15,16,17,18,21,22))

embryo_stage_day5 = subset(embryo_stage, embryo_stage$Stage=="day5")
embryoNumber_day5 = c(40)
cellNumber_day5 = list(c(7,8,9,10,11,12,13,14,15,17,18,19,21,22,24,25))

embryo_stage_day6 = subset(embryo_stage, embryo_stage$Stage=="day6")
embryoNumber_day6 = c(44,47)
cellNumber_day6 = list(c(1,2,4,5,6,7,8,9,10,11,13,14,15,16,17,18,22,24,25,26,28,29,31,32,33,35,36,37,38,39),c(15,16,17,18,20,21,22,23,24,25,26,27,28,29,30))
```



```{r}
fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber[1]), sep = ""), (unlist(cellNumber[1]))[1], sep = "_"), "txt", sep = ".")  
data_combined = read.table(fileName, sep = "\t", header = TRUE)
data_combined = data_combined[c(1:3)]

for (i in 1:length(embryoNumber)){
  for (n in 1:length(as.numeric(unlist(cellNumber[i])))){ 
    fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber[i]), sep = ""), (unlist(cellNumber[i]))[n], sep = "_"), "txt", sep = ".")  
    columnName = paste("LogR", paste(embryoNumber[i], (unlist(cellNumber[i]))[n], sep = "_"), sep = "_")
    data_combined[columnName] = read.table(fileName, sep = "\t", header = TRUE)[4]
  }
}
for (i in 1:(dim(data_combined)[2]-3)){
  columnName = paste(colnames(data_combined[i+3]), "ratio", sep = "_")
  data_combined[columnName] =  data_combined[i+3]/colMedians(as.matrix(data_combined[i+3]), na.rm = TRUE)
}
data_combined["combined_median"] = rowMedians(as.matrix(data_combined[((dim(data_combined)[2]-3)/2+4):(dim(data_combined)[2])]), na.rm = TRUE)
#data_combined
colnames(data_combined)

```
```{r fig.height=25, fig.width=12}
chromosomeNumber = c(seq(1,22), "X")

plot_logRratio = data.frame()
for (j in chromosomeNumber){
  plotData_ratio = subset(data_combined, (data_combined$chr==j))[c(2, ((dim(data_combined)[2]-3)/2+4):(dim(data_combined)[2]-1))]
  logR_ratio = melt(plotData_ratio, "start")
  logR_ratio$Chr = j
  plot_logRratio = rbind(plot_logRratio, logR_ratio)
}
plot_logRratio$facet= factor(plot_logRratio$Chr, levels = c(1:22, "X"))
plot = ggplot(plot_logRratio, aes(start, value, group=variable, color = variable)) +
  geom_point(size = 0.2) + 
  facet_wrap(~facet, scales = "free_x", ncol = 3) +
  labs(x = "Position", y = "logR", color = NULL) +
  theme(legend.position = "bottom")
print(plot)
```
Stage: DAY1

```{r}
fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day1[1]), sep = ""), (unlist(cellNumber_day1[1]))[1], sep = "_"), "txt", sep = ".")  
data_day1 = read.table(fileName, sep = "\t", header = TRUE)
data_day1 = data_day1[c(1:3)]

for (i in 1:length(embryoNumber_day1)){
  for (n in 1:length(as.numeric(unlist(cellNumber_day1[i])))){ 
    fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day1[i]), sep = ""), (unlist(cellNumber_day1[i]))[n], sep = "_"), "txt", sep = ".")  
    columnName = paste("LogR", paste(embryoNumber_day1[i], (unlist(cellNumber_day1[i]))[n], sep = "_"), sep = "_")
    data_day1[columnName] = read.table(fileName, sep = "\t", header = TRUE)[4]
  }
}
for (i in 1:(dim(data_day1)[2]-3)){
  columnName = paste(colnames(data_day1[i+3]), "ratio", sep = "_")
  data_day1[columnName] =  data_day1[i+3]/colMedians(as.matrix(data_day1[i+3]), na.rm = TRUE)
}
#data_day1
data_day1["day1_median"] = rowMedians(as.matrix(data_day1[((dim(data_day1)[2]-3)/2+4):(dim(data_day1)[2])]), na.rm = TRUE)
colnames(data_day1)
```
```{r fig.height=25, fig.width=12}
chromosomeNumber = c(seq(1,22), "X")

plot_logRratio = data.frame()
for (j in chromosomeNumber){
  plotData_ratio = subset(data_day1, (data_day1$chr==j))[c(2, ((dim(data_day1)[2]-3)/2+4):(dim(data_day1)[2]-1))]
  logR_ratio = melt(plotData_ratio, "start")
  logR_ratio$Chr = j
  plot_logRratio = rbind(plot_logRratio, logR_ratio)
}
plot_logRratio$facet= factor(plot_logRratio$Chr, levels = c(1:22, "X"))
plot = ggplot(plot_logRratio, aes(start, value, group=variable, color = variable)) +
  geom_point(size = 0.2) + 
  facet_wrap(~facet, scales = "free_x", ncol = 3) +
  labs(x = "Position", y = "logR", color = NULL) +
  theme(legend.position = "bottom")
print(plot)
```


Stage: DAY2

```{r}
fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day2[1]), sep = ""), (unlist(cellNumber_day2[1]))[1], sep = "_"), "txt", sep = ".")  
data_day2 = read.table(fileName, sep = "\t", header = TRUE)
data_day2 = data_day2[c(1:3)]

for (i in 1:length(embryoNumber_day2)){
  for (n in 1:length(as.numeric(unlist(cellNumber_day2[i])))){ 
    fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day2[i]), sep = ""), (unlist(cellNumber_day2[i]))[n], sep = "_"), "txt", sep = ".")  
    columnName = paste("LogR", paste(embryoNumber_day2[i], (unlist(cellNumber_day2[i]))[n], sep = "_"), sep = "_")
    data_day2[columnName] = read.table(fileName, sep = "\t", header = TRUE)[4]
  }
}
for (i in 1:(dim(data_day2)[2]-3)){
  columnName = paste(colnames(data_day2[i+3]), "ratio", sep = "_")
  data_day2[columnName] =  data_day2[i+3]/colMedians(as.matrix(data_day2[i+3]), na.rm = TRUE)
}
data_day2["day2_median"] = rowMedians(as.matrix(data_day2[((dim(data_day2)[2]-3)/2+4):(dim(data_day2)[2])]), na.rm = TRUE)
colnames(data_day2)
#data_day2
```
```{r fig.height=25, fig.width=12}
chromosomeNumber = c(seq(1,22), "X")

plot_logRratio = data.frame()
for (j in chromosomeNumber){
  plotData_ratio = subset(data_day2, (data_day2$chr==j))[c(2, ((dim(data_day2)[2]-3)/2+4):(dim(data_day2)[2]-1))]
  logR_ratio = melt(plotData_ratio, "start")
  logR_ratio$Chr = j
  plot_logRratio = rbind(plot_logRratio, logR_ratio)
}
plot_logRratio$facet= factor(plot_logRratio$Chr, levels = c(1:22, "X"))
plot = ggplot(plot_logRratio, aes(start, value, group=variable, color = variable)) +
  geom_point(size = 0.2) + 
  facet_wrap(~facet, scales = "free_x", ncol = 3) +
  labs(x = "Position", y = "logR", color = NULL) +
  theme(legend.position = "bottom")
print(plot)
```



Stage: DAY3
```{r}
fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day3[1]), sep = ""), (unlist(cellNumber_day3[1]))[1], sep = "_"), "txt", sep = ".")  
data_day3 = read.table(fileName, sep = "\t", header = TRUE)
data_day3 = data_day3[c(1:3)]

for (i in 1:length(embryoNumber_day3)){
  for (n in 1:length(as.numeric(unlist(cellNumber_day3[i])))){ 
    fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day3[i]), sep = ""), (unlist(cellNumber_day3[i]))[n], sep = "_"), "txt", sep = ".")  
    columnName = paste("LogR", paste(embryoNumber_day3[i], (unlist(cellNumber_day3[i]))[n], sep = "_"), sep = "_")
    data_day3[columnName] = read.table(fileName, sep = "\t", header = TRUE)[4]
  }
}
for (i in 1:(dim(data_day3)[2]-3)){
  columnName = paste(colnames(data_day3[i+3]), "ratio", sep = "_")
  data_day3[columnName] =  data_day3[i+3]/colMedians(as.matrix(data_day3[i+3]), na.rm = TRUE)
}
data_day3["day3_median"] = rowMedians(as.matrix(data_day3[((dim(data_day3)[2]-3)/2+4):(dim(data_day3)[2])]), na.rm = TRUE)
colnames(data_day3)
#data_day3
```

```{r fig.height=25, fig.width=12}
chromosomeNumber = c(seq(1,22), "X")

plot_logRratio = data.frame()
for (j in chromosomeNumber){
  plotData_ratio = subset(data_day3, (data_day3$chr==j))[c(2, ((dim(data_day3)[2]-3)/2+4):(dim(data_day3)[2]-1))]
  logR_ratio = melt(plotData_ratio, "start")
  logR_ratio$Chr = j
  plot_logRratio = rbind(plot_logRratio, logR_ratio)
}
plot_logRratio$facet= factor(plot_logRratio$Chr, levels = c(1:22, "X"))
plot = ggplot(plot_logRratio, aes(start, value, group=variable, color = variable)) +
  geom_point(size = 0.2) + 
  facet_wrap(~facet, scales = "free_x", ncol = 3) +
  labs(x = "Position", y = "logR", color = NULL) +
  theme(legend.position = "bottom")
print(plot)
```

Stage: DAY4
```{r}
fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day4[1]), sep = ""), (unlist(cellNumber_day4[1]))[1], sep = "_"), "txt", sep = ".")  
data_day4 = read.table(fileName, sep = "\t", header = TRUE)
data_day4 = data_day4[c(1:3)]

for (i in 1:length(embryoNumber_day4)){
  for (n in 1:length(as.numeric(unlist(cellNumber_day4[i])))){ 
    fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day4[i]), sep = ""), (unlist(cellNumber_day4[i]))[n], sep = "_"), "txt", sep = ".")  
    columnName = paste("LogR", paste(embryoNumber_day4[i], (unlist(cellNumber_day4[i]))[n], sep = "_"), sep = "_")
    data_day4[columnName] = read.table(fileName, sep = "\t", header = TRUE)[4]
  }
}
for (i in 1:(dim(data_day4)[2]-3)){
  columnName = paste(colnames(data_day4[i+3]), "ratio", sep = "_")
  data_day4[columnName] =  data_day4[i+3]/colMedians(as.matrix(data_day4[i+3]), na.rm = TRUE)
}
data_day4["day4_median"] = rowMedians(as.matrix(data_day4[((dim(data_day4)[2]-3)/2+4):(dim(data_day4)[2])]), na.rm = TRUE)
colnames(data_day4)
#data_day4
```

```{r fig.height=25, fig.width=12}
chromosomeNumber = c(seq(1,22), "X")

plot_logRratio = data.frame()
for (j in chromosomeNumber){
  plotData_ratio = subset(data_day4, (data_day4$chr==j))[c(2, ((dim(data_day4)[2]-3)/2+4):(dim(data_day4)[2]-1))]
  logR_ratio = melt(plotData_ratio, "start")
  logR_ratio$Chr = j
  plot_logRratio = rbind(plot_logRratio, logR_ratio)
}
plot_logRratio$facet= factor(plot_logRratio$Chr, levels = c(1:22, "X"))
plot = ggplot(plot_logRratio, aes(start, value, group=variable, color = variable)) +
  geom_point(size = 0.2) + 
  facet_wrap(~facet, scales = "free_x", ncol = 3) +
  labs(x = "Position", y = "logR", color = NULL) +
  theme(legend.position = "bottom")
print(plot)
```


Stage: DAY5
```{r}
fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day5[1]), sep = ""), (unlist(cellNumber_day5[1]))[1], sep = "_"), "txt", sep = ".")  
data_day5 = read.table(fileName, sep = "\t", header = TRUE)
data_day5 = data_day5[c(1:3)]

for (i in 1:length(embryoNumber_day5)){
  for (n in 1:length(as.numeric(unlist(cellNumber_day5[i])))){ 
    fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day5[i]), sep = ""), (unlist(cellNumber_day5[i]))[n], sep = "_"), "txt", sep = ".")  
    columnName = paste("LogR", paste(embryoNumber_day5[i], (unlist(cellNumber_day5[i]))[n], sep = "_"), sep = "_")
    data_day5[columnName] = read.table(fileName, sep = "\t", header = TRUE)[4]
  }
}
for (i in 1:(dim(data_day5)[2]-3)){
  columnName = paste(colnames(data_day5[i+3]), "ratio", sep = "_")
  data_day5[columnName] =  data_day5[i+3]/colMedians(as.matrix(data_day5[i+3]), na.rm = TRUE)
}
data_day5["day5_median"] = rowMedians(as.matrix(data_day5[((dim(data_day5)[2]-3)/2+4):(dim(data_day5)[2])]), na.rm = TRUE)
colnames(data_day5)
#data_day5
```

```{r fig.height=16, fig.width=12}
chromosomeNumber = c(seq(1,22), "X")

plot_logRratio = data.frame()
for (j in chromosomeNumber){
  plotData_ratio = subset(data_day5, (data_day5$chr==j))[c(2, ((dim(data_day5)[2]-3)/2+4):(dim(data_day5)[2]-1))]
  logR_ratio = melt(plotData_ratio, "start")
  logR_ratio$Chr = j
  plot_logRratio = rbind(plot_logRratio, logR_ratio)
}
plot_logRratio$facet= factor(plot_logRratio$Chr, levels = c(1:22, "X"))
plot = ggplot(plot_logRratio, aes(start, value, group=variable, color = variable)) +
  geom_point(size = 0.2) + 
  facet_wrap(~facet, scales = "free_x", ncol = 3) +
  labs(x = "Position", y = "logR", color = NULL) +
  theme(legend.position = "bottom")
print(plot)
```

Stage: DAY6
```{r}
fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day6[1]), sep = ""), (unlist(cellNumber_day6[1]))[1], sep = "_"), "txt", sep = ".")  
data_day6 = read.table(fileName, sep = "\t", header = TRUE)
data_day6 = data_day6[c(1:3)]

for (i in 1:length(embryoNumber_day6)){
  for (n in 1:length(as.numeric(unlist(cellNumber_day6[i])))){ 
    fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn2/cn2_TVEMB", (embryoNumber_day6[i]), sep = ""), (unlist(cellNumber_day6[i]))[n], sep = "_"), "txt", sep = ".")  
    columnName = paste("LogR", paste(embryoNumber_day6[i], (unlist(cellNumber_day6[i]))[n], sep = "_"), sep = "_")
    data_day6[columnName] = read.table(fileName, sep = "\t", header = TRUE)[4]
  }
}
for (i in 1:(dim(data_day6)[2]-3)){
  columnName = paste(colnames(data_day6[i+3]), "ratio", sep = "_")
  data_day6[columnName] =  data_day6[i+3]/colMedians(as.matrix(data_day6[i+3]), na.rm = TRUE)
}
data_day6["day6_median"] = rowMedians(as.matrix(data_day6[((dim(data_day6)[2]-3)/2+4):(dim(data_day6)[2])]), na.rm = TRUE)
colnames(data_day6)
(dim(data_day6)[2]-3)/2
#data_day6
```



```{r fig.height=25, fig.width=12}
chromosomeNumber = c(seq(1,22), "X")

plot_logRratio = data.frame()
for (j in chromosomeNumber){
  plotData_ratio = subset(data_day6, (data_day6$chr==j))[c(2, ((dim(data_day6)[2]-3)/2+4):(dim(data_day6)[2]-1))]
  logR_ratio = melt(plotData_ratio, "start")
  logR_ratio$Chr = j
  plot_logRratio = rbind(plot_logRratio, logR_ratio)
}
plot_logRratio$facet= factor(plot_logRratio$Chr, levels = c(1:22, "X"))
plot = ggplot(plot_logRratio, aes(start, value, group=variable, color = variable)) +
  geom_point(size = 0.2) + 
  facet_wrap(~facet, scales = "free_x", ncol = 3) +
  labs(x = "Position", y = "logR", color = NULL) +
  theme(legend.position = "bottom")
print(plot)
```


```{r fig.height=16, fig.width=12}
data_stage = cbind(data_combined[c(1,2,3,ncol(data_combined))], data_day1[ncol(data_day1)], data_day2[ncol(data_day2)], data_day3[ncol(data_day3)], data_day4[ncol(data_day4)], data_day5[ncol(data_day5)], data_day6[ncol(data_day6)])

#dim(data_stage)[2]
for (i in 5:ncol(data_stage)){
  plot_logRratio = data.frame()
  for (j in chromosomeNumber){
    plotData_ratio = subset(data_stage, (data_stage$chr==j))[c(2,4,i)]
    logR_ratio = melt(plotData_ratio, "start")
    logR_ratio$Chr = j
    plot_logRratio = rbind(plot_logRratio, logR_ratio)
  }
  plot_logRratio$facet= factor(plot_logRratio$Chr, levels = c(1:22, "X"))
  plot = ggplot(plot_logRratio, aes(start, value, group=variable, color = variable)) +
    geom_point(size = 0.1) + 
    facet_wrap(~facet, scales = "free_x", ncol = 3) +
    ylim(-50,50) +
    labs(x = "Position", y = "logR_ratio", color = NULL) +
    theme(legend.position = "bottom")
  print(plot)
}
```

