---
title: "R Notebook"
output: html_notebook
---



```{r}
library(openxlsx)
library(reshape)
library(ggplot2)
library(gridExtra)

stimulate_dataset_list = loadWorkbook('Stimulate dataset list.xlsx')
# Renaming sheets to removes spaces in names
sheetNames = sheets(stimulate_dataset_list)
sheetNames = lapply(sheetNames, trimws) # Trimming away trailing space

newSheetNames = c()
for (sheetName in sheetNames) {
  sheetName = gsub(" ", "_", sheetName)
  newSheetNames[sheetName] = sheetName 
}
sheetNames = newSheetNames

# Assigning each sheet to a dataframe
for(i in 1:length(sheetNames)){
  assign(sheetNames[i],readWorkbook(stimulate_dataset_list,sheet = i))
}

Single_CNV = Single_CNV[-1,]
colnames(Single_CNV) = c("total_number_of_samples", "length", "cn2_number_of_samples", "cn2_proportion", "cn1_number_of_samples", "cn1_proportion", "cnv_size", "size_proportion", "cn1_start", "cn1_end",  "cn3_number_of_samples", "cn3_proportion", "cnv_size", "size_proportion", "cn3_start", "cn3_end")

CN1_CN3 = CN1_CN3[-1,]
colnames(CN1_CN3) = c("total_number_of_samples", "length", "cn2_number_of_samples", "cn2_proportion", "cn1_number_of_samples", "cn1_proportion", "cnv_size", "size_proportion", "cn1_start", "cn1_end",  "cn3_number_of_samples", "cn3_proportion", "cnv_size", "size_proportion", "cn3_start", "cn3_end")
```



```{r, fig.height=16, fig.width=12}
gamma = 15


for (row_number in 1:nrow(Single_CNV)){
  length = as.numeric(Single_CNV$length[row_number])
  cn1_start_position = as.numeric(Single_CNV$cn1_start[row_number])
  cn3_start_position = as.numeric(Single_CNV$cn3_start[row_number])
  
  cnv_size = as.numeric(Single_CNV$cnv_size[row_number])
  
  total_number = as.numeric(Single_CNV$total_number_of_samples[row_number])
  number_no_cnv = as.numeric(Single_CNV$cn2_number_of_samples[row_number])
  number_cnv_cn1 = as.numeric(Single_CNV$cn1_number_of_samples[row_number])
  number_cnv_cn3 = as.numeric(Single_CNV$cn3_number_of_samples[row_number])
  
  for (n in 1:5){
    ori_data_filename = paste(paste(paste(paste(paste(paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/stimulate data/Data/SD_",total_number,sep = ""), number_no_cnv,sep = "_"), number_cnv_cn1, sep = "_"), number_cnv_cn3, sep = "_"), cnv_size, sep = "_"), "run", sep = "_"), n, sep = ""), "csv", sep = ".")
    ori_data = read.csv(file = ori_data_filename, header = TRUE, sep = ",")
    
    fllat_filename = writeFileName = paste(paste(paste(paste(paste(paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/stimulate data/FLLat/Result/SD", total_number,sep = "_"), number_no_cnv,sep = "_"), number_cnv_cn1, sep = "_"), number_cnv_cn3, sep = "_"), cnv_size, sep = "_"), "run", sep = "_"), n, sep = ""), "csv", sep = ".")
    fllat_data = read.csv(file = fllat_filename, header = TRUE, sep = ",")

    for (m in (number_no_cnv+1):total_number){
      graph_name = paste(paste(paste(paste(paste(paste(paste(paste(paste(paste(gamma,"",sep = ""), "SD", sep = "_"), total_number,sep = "_"), number_no_cnv,sep = "_"), number_cnv_cn1, sep = "_"), number_cnv_cn3, sep = "_"), cnv_size, sep = "_"), m, sep = "_sample"), "run", sep = "_"), n, sep = "")
      plotName = paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/stimulate data/FLLat/Graph", paste(graph_name, "pdf", sep = "."), sep = "/")
      pdf(plotName, height = 16, width = 12)
      plot_ori_data = ori_data[2+m]
      position = c(1:1000)
      data = cbind(position, plot_ori_data)
      result.plot = melt(data, "position")
      if (m<=number_no_cnv){
        plot1 = ggplot(data=result.plot) + 
          geom_point(aes(position, value), size = 1, color = "red") + 
          geom_segment(aes(x = 1, y = 2, xend = length, yend = 2), color = "black", size = 1) +
          ylim(-4,4) +
          ggtitle(graph_name)
      }
      else{
        plot1 = ggplot(data=result.plot) + 
          geom_point(aes(position, value), size = 1, color = "red") + 
          geom_segment(aes(x = 1, y = 2, xend = cn1_start_position-1, yend = 2), color = "black", size = 1) +
          geom_segment(aes(x = 1, y = 2, xend = cn3_start_position-1, yend = 2), color = "black", size = 1) +
          geom_segment(aes(x = cn1_start_position, y = 1, xend = cn1_start_position+cnv_size-1, yend = 1), color = "black", size = 1) +
          geom_segment(aes(x = cn3_start_position, y = 3, xend = cn3_start_position+cnv_size-1, yend = 3), color = "black", size = 1) +
          geom_segment(aes(x = cn1_start_position+cnv_size, y = 2, xend = length, yend = 2), color = "black", size = 1) +
          geom_segment(aes(x = cn3_start_position+cnv_size, y = 2, xend = length, yend = 2), color = "black", size = 1) +
          ylim(-4,4) +
          ggtitle(graph_name)
      }
      
      plot_fllat = fllat_data[c(3+m,3+m+2*total_number)]
      position = c(1:1000)
      data = cbind(position, plot_fllat)
      result.plot = melt(data, "position")
      plot2 = ggplot(data=result.plot) + 
        geom_point(aes(position, value, group=variable, color = variable), size = 1) + 
        theme(legend.position = "none") +
        ylim(-4,4) 
      
      
      print(grid.arrange(plot1, plot2, nrow = 2))
      dev.off()
      
    }
  }
}

```
