---
title: "R Notebook"
output: html_notebook
---

```{r}
embryoNumber = c(17) #c(41)
cellNumber = c(2,3,5,7,8,9,10) #c(1,2,3,4,5,6,7)

fileName = paste(paste(paste("/Users/Yibing/Bioinfo-Master-Thesis/Data/logr_cn_per_bin/TVEMB", embryoNumber, sep = ""), cellNumber[1], sep = "_"), "250K.101.sorted.count.gamma_15.gc_corrected.segments.copynumber.txt", sep = ".")  
binList = read.table(fileName, sep = "\t", header = TRUE)[c(1:3)]
```

read in Matlab results
```{r}
file_low_rank = paste(paste("embryo", embryoNumber, sep = ""), "_low_rank_component.csv", sep = "")
file_sparse = paste(paste("embryo", embryoNumber, sep = ""), "_sparse_component.csv", sep = "")

embryo_low_rank_component = read.csv(file = file_low_rank, header = FALSE, sep = ",")
embryo_sparse_component = read.csv(file = file_sparse, header = FALSE, sep = ",")
```



```{r}
colnames(embryo_low_rank_component) = paste(embryoNumber, cellNumber, sep = "_")
colnames(embryo_sparse_component) = paste(embryoNumber, cellNumber, sep = "_")
embryo_low_rank_component = cbind(binList, embryo_low_rank_component)
embryo_sparse_component = cbind(binList, embryo_sparse_component)

embryo_low_rank_component
embryo_sparse_component
```

#plotting low-rank component against chromosome
```{r fig.height=16, fig.width=12}
chromosomeNumber = c(seq(1,22), "X")
result.plot = embryo_low_rank_component

for (i in 1:length(cellNumber)){ 
  plotName = paste(colnames(result.plot)[i+3], ".pdf", sep = "_PLA_LR_")
  pdf(plotName, height = 16, width = 12)
  result.plot$facet= factor(result.plot$chr, levels = c(1:22, "X"))
  plot = ggplot(data=result.plot) + 
    geom_point(aes(x = start, y = result.plot[ ,i+3]), size = 0.2, color = "red") + 
    ylim(-1,1) +
    facet_wrap(.~facet, ncol = 3, scales = "free_x") +
    labs(x = "Start", y = "logR", color = NULL) +
    ggtitle(names(result.plot)[i+3]) +
    theme(legend.position = "bottom")
  print(plot)
  dev.off()
}
```

#plotting sparse component against chromosome
```{r fig.height=16, fig.width=12}
chromosomeNumber = c(seq(1,22), "X")
result.plot = embryo_sparse_component

for (i in 1:length(cellNumber)){ 
  plotName = paste(colnames(result.plot)[i+3], ".pdf", sep = "_PLA_S_")
  pdf(plotName, height = 16, width = 12)
  result.plot$facet= factor(result.plot$chr, levels = c(1:22, "X"))
  plot = ggplot(data=result.plot) + 
    geom_point(aes(x = start, y = result.plot[ ,i+3]), size = 0.2, color = "red") + 
    ylim(-1,1) +
    facet_wrap(.~facet, ncol = 3, scales = "free_x") +
    labs(x = "Start", y = "logR", color = NULL) +
    ggtitle(names(result.plot)[i+3]) +
    theme(legend.position = "bottom")
  print(plot)
  dev.off()
}
```